### ISSUE TITLE
JSON contains useless values

### ISSUE THREAD

**Issue by zeromancer1972** [icstechsales/dql-explorer#3] opened 2019-03-08 11:56 UTC
It happened to me that the JSON for the fieldnames of a form were empty. You could check that and then omit this element in the generated JSON

**Comment by scott-good** [comment] 2019-03-08 17:10
This may have been caused by an issue we addressed this morning. We found that Image Resources were being collected in the db.Forms method. This was causing server issues and has been corrected. Potentially also from one of the field types we aren't collecting (of which there are quite a few).

**Comment by scott-good** [comment] 2019-03-08 17:10
UGH. Sorry. Didn't mean to close it!

**Comment by dprosper** [comment] 2019-03-10 22:01
Thank your for reporting. We've address this in a new release https://github.com/icstechsales/dql-explorer/releases

**Closed as completed by dprosper** 2019-03-10 22:01 UTC
